[package]
name = "rust_basics"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version = "0.11", features = ["blocking", "json"]}
error-chain = "0.12.4"
tokio = {version = "1", features = ["full"] }